repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-builtin-literals
      - id: trailing-whitespace
        exclude_types:
          - "markdown"
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [ --config=pyproject.toml ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [ --config=pyproject.toml ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [ --settings-path=pyproject.toml ]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [ commit ]
        language: system
        entry: poetry run mypy
        types: [ python ]
        pass_filenames: false

      - id: requirements
        name: Requirements
        entry: poetry export --format=requirements.txt --without-hashes --extras "links_to_ids" --output=requirements.txt
        pass_filenames: false
        language: system
