[tool.poetry]
name = "droos-bot"
version = "0.1.0"
description = ""
authors = ["yshalsager <ysh-alsager@hotmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
python-telegram-bot = "^13.11"
python-telegram-bot-pagination = "^0.0.2"
gspread = "^5.1.1"
gspread-pandas = "^3.0.4"
SQLAlchemy = "^1.4.31"
Pyrogram = { version = "^1.4.7", optional = true }
TgCrypto = { version = "^1.2.3", optional = true }
convopyro = { git = "https://github.com/Ripeey/Conversation-Pyrogram.git", rev = "4572b4d", optional = true }

[tool.poetry.dev-dependencies]
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
